env:
  browser: true
  es6: true
  commonjs: true
  jest: true
extends:
  - 'airbnb'
  - 'airbnb/hooks'
  - 'airbnb-typescript'
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module
plugins:
  - 'react'
  - '@typescript-eslint'
settings:
  react:
    version: '17'
rules: {
  'react/jsx-one-expression-per-line': 'off',
  'react/prop-types': 'off',
  'no-case-declarations': 'off',
}
