export const FETCH_ALL_POKEMONS_SUCCESS = 'FETCH_ALL_POKEMONS_SUCCESS';
export const FETCH_ALL_POKEMONS_FAILURE = 'FETCH_ALL_POKEMONS_FAILURE';

export const CATCH_POKEMON_SUCCESS = 'CATCH_POKEMON_SUCCESS';
export const CATCH_POKEMON_FAILURE = 'CATCH_POKEMON_FAILURE';

export const SET_FILTER = 'SET_FILTER';
export const ADD_SHOWN_POKEMONS = 'ADD_SHOWN_POKEMONS';
export const RESET_SHOWN_POKEMONS = 'RESET_SHOWN_POKEMONS';
