// export const FETCH_ALL_POKEMONS_REQUEST = 'FETCH_ALL_POKEMONS_REQUEST';
export const FETCH_POKEMONS_SUCCESS = 'FETCH_POKEMONS_SUCCESS';
export const FETCH_POKEMONS_FAILURE = 'FETCH_POKEMONS_FAILURE';

// export const FETCH_USER_POKEMONS_REQUEST = 'FETCH_USER_POKEMONS_REQUEST';
// export const FETCH_USER_POKEMONS_SUCCESS = 'FETCH_USER_POKEMONS_SUCCESS';
// export const FETCH_USER_POKEMONS_FAILURE = 'FETCH_USER_POKEMONS_FAILURE';

export const CATCH_POKEMON_REQUEST = 'CATCH_POKEMON_REQUEST';
export const CATCH_POKEMON_SUCCESS = 'CATCH_POKEMON_SUCCESS';
export const CATCH_POKEMON_FAILURE = 'CATCH_POKEMON_FAILURE';

export const SET_FILTER = 'SET_FILTER';
export const ADD_SHOWN_POKEMONS = 'ADD_SHOWN_POKEMONS';
export const RESET_SHOWN_POKEMONS = 'RESET_SHOWN_POKEMONS';
